# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Liturgical Books'
description:      'A sampler of RBML Liturgical Books'
url:              ''
baseurl:          '/liturgical'
copyright:        'CC-BY 4.0 International'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

theme:            wax_theme
permalink:        'pretty'
safe:             true
exclude:          [Gemfile*, Rakefile, vendor, spec, README.md, wax_theme]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  # qatar: # name of collection
  #   output: true # makes sure pages are output as html files
  #   layout: 'qatar_item' # the layout for the pages to use
  #   metadata:
  #     source: 'qatar.csv' # path to the metadata file within `_data`
  #   images:
  #     source: 'raw_images/qatar' # path to the directory of images within `_data`

  liturgical:
    output: true
    layout: 'liturgical_item'
    metadata:
      source: 'liturgical.csv'
    images:
      source: 'raw_images/liturgical'

# --------------------------------------------------------------
# LUNR SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple lunr indexes below (though only one is
# recommended!) by specifying
# a `file` to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:lunr` .
# You can optionally generate a default UI by specifying a UI file
# and running `$ bundle exec rake wax:lunr UI=true`.

lunr_index:
  - file: 'js/lunr-index.json' # file the index will get written to
    ui:   'js/lunr-ui.js' # path to the search UI file
    collections:
      liturgical:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - tag
          - label

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Credits'
    link: '/credits/'
  - label: 'Exhibits'
    link: /exhibits/toc/
  - label: 'Reuse'
    link: '/reuse/'
    # sub:
    #   - label: 'Books of the Mass'
    #     link: '/exhibits/booksofthemass/'
    #   - label: 'Books of the Office'
    #     link: '/exhibits/booksoftheoffice/'
    #   - label: 'Calendar'
    #     link: '/exhibits/calendar/'
    #   - label: 'Chant Books of the Mass'
    #     link: '/exhibits/chantbooksofthemass/'
    #   - label: 'Chapter'
    #     link: '/exhibits/chapter/'
    #   - label: 'Common Versus Proper'
    #     link: '/exhibits/commonversusproper/'
    #   - label: 'Computus'
    #     link: '/exhibits/computus/'
    #   - label: 'Directions'
    #     link: '/exhibits/directions/'
    #   - label: 'Home'
    #     link: '/exhibits/homepage/'
    #   - label: 'Liturgical Year'
    #     link: '/exhibits/liturgicalyear/'
    #   - label: 'Organization of Liturgical Books'
    #     link: '/exhibits/organizationofliturgicalbooks/'
    #   - label: 'The Divine Office'
    #     link: '/exhibits/thedivineoffice/'
    #   - label: 'The Mass'
    #     link: '/exhibits/themass/'
    #   - label: 'Web Resources'
    #     link: '/exhibits/webresources/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/minicomp/wax'
    - label: 'Credits'
      link: '/credits'
    - label: 'Contact'
      link: 'https://gitter.im/minicomp/wax/'
  logos:
    - img: 'logo.png'
    - img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2r40VYrf2Q5jkJiPGjPkl7xZoHJliwgVtHCLVXmAsRKw0ZudD'
      link: 'https://library.columbia.edu'

## Kramdown instructions

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# FIN